name: llama3-8b
modelID: "meta-llama/Meta-Llama-3-8B-Instruct"

modelConfig:
  maxModelLen: 8192
  maxConcurrency: 4
  numOfGPU: 2
  numOfCPU: 6

service:
  backend: "vLLM"
  openAICompatible: true
  minReplica: 1
  maxReplica: 4
  gpu: "g5"
# use default for all other values